---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

**Note:** we assume that the activity.csv file is in the working directory.

Loading the data in a varable: 
`activity_data <- read.csv("activity.csv")`

Formating the dates: 
`activity_data$date <- as.Date(activity_data$date)`

## What is mean total number of steps taken per day?

#### Ignoring the missing values in the dataset
```
x <- complete.cases(activity_data)
existing_activity<- activity_data[x,]
```

### Make a histogram of the total number of steps taken each day
```
activity_per_day <- aggregate(existing_activity[,1],list(date= existing_activity$date),sum)
hist(activity_per_day$x, xlab="Steps", main="Steps Taken Each Day")
```

### Calculate and report the **mean** and **median** total number of steps taken per day
Calculate mean:
`total_steps_mean <- mean(activity_per_day$x,na.rm=TRUE)`


Calculate mean:
`total_steps_median <- median(activity_per_day$x, na.rm=TRUE)`

## What is the average daily activity pattern?

### Make a time series plot (i.e. `type = "l"`) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
```
agg_int <-  aggregate(existing_activity[,1],list(interval= existing_activity$interval),mean)
with(agg_int,plot(interval,x,type="l", ylab="daily average for interval"))
```

### Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
`max_step_interval <- agg_int[agg_int$x== max(agg_int[,2]),1]`

## Imputing missing values

### Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with `NAs`)
`empty_rows <- nrow(activity_data[!x,])`

### Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.
```
extended_activity_data <- merge(activity_data, agg_int)
extended_activity_data[!complete.cases(extended_activity_data),2]<- extended_activity_data[!complete.cases(extended_activity_data),4]
```

### Create a new dataset that is equal to the original dataset but with the missing data filled in.
`new_activity_data <- extended_activity_data[,1:3]`

### Make a histogram of the total number of steps taken each day. 
```
new_activity_per_day <- aggregate(new_activity_data[,2],list(date= new_activity_data$date),sum)
hist(new_activity_per_day$x, xlab="total steps per day", main="Steps per day for New Activity Data")
```

### Calculate and report the mean and median total number of steps taken per day.
```
new_total_steps_mean <-  mean(new_activity_per_day$x,na.rm=TRUE)
new_total_steps_median <- median(new_activity_per_day$x, na.rm=TRUE)
```

## Are there differences in activity patterns between weekdays and weekends?

### Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.
```
set_day_type <- function(x) {

    if (weekdays(as.Date(x)) == "Sunday" | weekdays(as.Date(x)) == "Saturday") 
       day_type <- "weekend"
    else
        day_type <- "weekday"

    day_type    
}
new_activity_data$day_type <- as.factor(sapply(new_activity_per_day[,1],set_day_type))
```

### Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis).

```
par(mfrow = c(2, 1))

wkday <-  aggregate(steps~interval,new_activity_data,mean, subset= new_activity_data$wkday=="weekday")
with(wkday,plot(interval,steps,type="l", main="weekday average for 5 min interval"))

wkend <-  aggregate(steps~interval,new_activity_data,mean, subset= new_activity_data$wkday=="weekend")
with(wkend,plot(interval,steps,type="l", main="weekend average for 5 min interval"))
```


#### Exporting html and md file using knitr package
install.packages('knitr', dependencies = TRUE)
library("knitr")
